<b>

1.Zero dimentional array

2.np.array

3.np.zeros()

4.np.arange()

5.np.shape

6.np.ndim

7.np.reshape()

8 np.gentext()

9.np.squeeze()

10.np.expand_dims()

11.np.concatenate()

12.np.stack()

13.np.hstack()
    </b>

In [60]:
import numpy as np

In [63]:
zero_dim=np.array(10079007).ndim
zero_dim

0

In [66]:
one_dim=np.ones(10)
one_dim

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
ndim_array=np.ones(shape=(5,2))
ndim_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
ndim_array2=np.array([[10,2],[10,2]],ndmin=3)
ndim_array2

array([[[10,  2],
        [10,  2]]])

In [68]:
print("Shape: ",one_dim.shape)
print("Size: ",one_dim.size)

Shape:  (10,)
Size:  10


In [88]:


A=np.arange(9)
B=np.arange(9)
A=A.reshape(3,3,1)
B=B.reshape(3,3)

In [89]:
A

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [15]:
A.shape

(3, 3, 1)

In [27]:
C=A.squeeze(axis=None)
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
B.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
B=np.expand_dims(B,axis=2)
B

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [93]:
B.shape

(3, 3, 1)

In [43]:
a=np.ones(10).reshape(1,2,5)
a.shape

(1, 2, 5)

In [44]:
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [47]:
b=np.array([1,2,3])
b.shape

(3,)

In [52]:
b=np.array([1,2,3],ndmin=2)
b.shape

(1, 3)

In [53]:
b=np.array([[1,2,3]])
b.shape

(1, 3)

In [56]:
arr=np.genfromtxt(r'C:\Users\Tnluser\Documents\Scalar\nparray.csv',delimiter=",",dtype=int,skip_header=1)
arr

array([[  1, 100],
       [  2,  20],
       [  4, 100]])

In [57]:
arr.size

6

In [59]:
arr.ndim

2

In [108]:
arr=np.ones(6).reshape(2,3)

In [109]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
arr.shape[1]

3

In [114]:
arr2=np.zeros([4,5],dtype=int)
arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [118]:
arr2[1,1:(arr.shape[1]+1)]=arr[1:(arr.shape[1]+1)]

In [117]:
arr[1:(arr.shape[1]+1)]

array([[1., 1., 1.]])

In [119]:
arr2

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [121]:
np.zeros(arr.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [136]:
mat=np.arange(20).reshape(5,4)

In [137]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

<h1> Padding </h1>

In [138]:
mat[1:-1,1:-1]


array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [139]:
mat[1:-1,1:-1]=np.zeros((3,2))
mat

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11],
       [12,  0,  0, 15],
       [16, 17, 18, 19]])

In [148]:
a1=np.arange(10)
a2=np.arange(11,21)

In [146]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
a2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [154]:
np.stack((a1,a2),axis=1)

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16],
       [ 6, 17],
       [ 7, 18],
       [ 8, 19],
       [ 9, 20]])

In [159]:
a3=np.arange(10).reshape(2,5)
a4=np.arange(11,21).reshape(2,5)
print(a3)
print("\n",a4)

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [[11 12 13 14 15]
 [16 17 18 19 20]]


In [188]:
np.concatenate((a3,a4),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [189]:
np.concatenate((a3,a4),axis=1)

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [161]:
np.stack((a3,a4),axis=2)

array([[[ 0, 11],
        [ 1, 12],
        [ 2, 13],
        [ 3, 14],
        [ 4, 15]],

       [[ 5, 16],
        [ 6, 17],
        [ 7, 18],
        [ 8, 19],
        [ 9, 20]]])

In [176]:
print(a3)
print()
print(a4)
print("\nStack with axis=1")
print(np.stack((a3,a4),axis=1))
print("\nStack with axis=2")
print(np.stack((a3,a4),axis=2))
print("\nV Stack---along columns")
print(np.vstack((a3,a4)))
print("\nH Stack----along rows")

print(np.hstack((a3,a4)))
print("\nDStack---along height")
print(np.dstack((a3,a4)))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

Stack with axis=1
[[[ 0  1  2  3  4]
  [11 12 13 14 15]]

 [[ 5  6  7  8  9]
  [16 17 18 19 20]]]

Stack with axis=2
[[[ 0 11]
  [ 1 12]
  [ 2 13]
  [ 3 14]
  [ 4 15]]

 [[ 5 16]
  [ 6 17]
  [ 7 18]
  [ 8 19]
  [ 9 20]]]

V Stack---along columns
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [11 12 13 14 15]
 [16 17 18 19 20]]

H Stack----along rows
[[ 0  1  2  3  4 11 12 13 14 15]
 [ 5  6  7  8  9 16 17 18 19 20]]

DStack---along height
[[[ 0 11]
  [ 1 12]
  [ 2 13]
  [ 3 14]
  [ 4 15]]

 [[ 5 16]
  [ 6 17]
  [ 7 18]
  [ 8 19]
  [ 9 20]]]


In [177]:
a5=np.arange(0,10)
a6=np.arange(10,20)


In [184]:
np.concatenate((a5,a6))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [179]:
print(a5)
print()
print(a6)
print("\nStack with axis=0")
print(np.stack((a5,a6),axis=1))
print("\nStack with axis=1")
print(np.stack((a5,a6),axis=1))
print("\nV Stack---along columns")
print(np.vstack((a5,a6)))
print("\nH Stack----along rows")

print(np.hstack((a5,a6)))
print("\nDStack---along height")
print(np.dstack((a5,a6)))

[0 1 2 3 4 5 6 7 8 9]

[10 11 12 13 14 15 16 17 18 19]

Stack with axis=0
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

Stack with axis=1
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

V Stack---along columns
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

H Stack----along rows
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

DStack---along height
[[[ 0 10]
  [ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]]]
