In [10]:
import numpy as np

In [11]:
#series of odd  number
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
d=np.array([[1,2,3,5],[4,5,6,0],[1,2,3,0]])
d

array([[1, 2, 3, 5],
       [4, 5, 6, 0],
       [1, 2, 3, 0]])

In [28]:
d.shape

(3, 4)

In [32]:
len(d) #number of rows or comma seperated values

3

In [31]:
d.ndim

2

In [33]:
d.size  #number of elements

12

In [35]:
d*10 #multiply all elements by 10

array([[10, 20, 30, 50],
       [40, 50, 60,  0],
       [10, 20, 30,  0]])

In [36]:
d[0]

array([1, 2, 3, 5])

In [37]:
d[0][0],d[0][2]

(1, 3)

In [38]:
#alternate way
d[0][[0,2]]

array([1, 3])

In [41]:
d


array([[1, 2, 3, 5],
       [4, 5, 6, 0],
       [1, 2, 3, 0]])

In [42]:
#row index followed by column index
d[0,1]

2

In [44]:
#row index=1, column index=3
d[1,3]

0

In [45]:
# fetch together 3 row=0, column=2
# fetch together 5 row=1, column=1
rows=[0,1]
columns=[2,1]

d[rows,columns]


array([3, 5])

In [47]:
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

<h1> Masking </h1>

In [51]:
mask= a%2==0 #mask  is condition
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [52]:
a[mask] # return values where mask is true

array([ 0,  2,  4,  6,  8, 10])

In [54]:
b=np.array([1,100])
b


array([  1, 100])

In [57]:
b[[False,True]]

array([100])

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
#elements divisible 2 or 3
mask_2= a%2==0
mask_2

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [65]:
mask_3= a%3==0
mask_3

array([ True, False, False,  True, False, False,  True, False, False,
        True, False])

In [70]:
# or is a bit wise operator , this | is element wise comparison
mask= (a%2==0) | (a%3==0)
mask

array([ True, False,  True,  True,  True, False,  True, False,  True,
        True,  True])

In [71]:
a[mask]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [72]:
array2=np.arange(0,101)

In [73]:
array2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [75]:
# replace even number with string even and odd number with string odd
mask_even=array2%2==0
mask_even

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

# where handles if else function

In [77]:
np.where(array2%2==0, 'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even'], dtype='<U4')

In [78]:
array2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [79]:
# sensor which measure heights in inches 
#goes faulty gives -1 when there is a fault
#remove the faulty values

heights=np.array([67.5,89, -1, 66.5, -1, 55.5])
heights

array([67.5, 89. , -1. , 66.5, -1. , 55.5])

In [ ]:
# mask_heights= heights!=-1
mask_heights

In [84]:

heights[mask_heights]

array([67.5, 89. , 66.5, 55.5])

In [86]:
# using where the same condition
mask_h=np.where(heights!=-1,True,False)
heights[mask_h]

array([67.5, 89. , 66.5, 55.5])

# NPS
<b> Net Promotor Score </b>

In [94]:
path=r'C:\Users\Tnluser\Desktop\Python_Libraries\survey.txt'
#r converts raw string to raw

In [97]:
score=np.loadtxt(path)
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [98]:
score=np.loadtxt(path,dtype=int)
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [99]:
score.size

1167

In [101]:
score.min()

1

In [103]:
score.max()

10

<b> Lets calculte NPS using this data </b>

NPS= % Promoters- % Detractors

Now, in order to calculate NPS we need the following two things:
% Promoters
% Detractors

In [104]:
total_population=score.size

In [105]:
detractors=score[score<=6]
detractors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [115]:
total_detractors=detractors.sum()
total_detractors

1080

In [112]:
number_detractors=detractors.size
number_detractors

332

In [113]:
passive=score[(score>=7) & (score<=8)]
passive.size

226

In [114]:
promotors=score[score>=9]
promotors

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [117]:
number_promotors=promotors.size

number_promotors

609

In [119]:
total_promotors=promotors.sum()
total_promotors

5696

In [125]:
percentage_Promotors= round((number_promotors/total_population)*100,2)
percentage_Promotors

52.19

In [126]:
percentage_detractors=round((number_detractors/total_population)*100,2)
percentage_detractors

28.45

In [128]:
NPS= percentage_Promotors-percentage_detractors
NPS

23.74